### PR TITLE
Contact us page

### PR DESCRIPTION
**Pull request by masakiasanuma**
This PR adds the contact page that can be navigated through the sidebar. The submit button doesn't do anything yet, but we can add in the appropriate email to send the message once we get confirmation from the client. 

I also re-organized/fixed some padding/margin stuff.

Let me know if there are any issues!

Screen Shot 2022-01-26 at 12 44 26 PM

### CODE REVIEW

**Comment by valistelea** [comment]
Looks really good, love the minimalistic yet beautiful design. I was wondering did you end up using the 123forms or how are you storing the requests and any information put into them?

**Review by valistelea — APPROVED** [review]
Great job! Thank you for doing the universal fix for the padding issue.

**Comment by masakiasanuma** [comment]
> Looks really good, love the minimalistic yet beautiful design. I was wondering did you end up using the 123forms or how are you storing the requests and any information put into them?

Thanks for the comment! I ended up not using 123forms for now since I figured we shouldn't send any email to anyone yet until the whole site is done. I was thinking we can use [EmailJS](https://www.emailjs.com/) to send the message to some email, or I might just redo it using 123forms, but for now I think having this structure is fine.

**Review by kevinquayle — APPROVED** [review]
Looks great and straight-forward! This is a small thing, but I think adding some space between the header and contact form, as well as increasing the font size of the form headers (maybe 25-30px or so) / overall size of the form would increase readability and fill the page better. Overall great work.

**Comment by masakiasanuma** [comment]
> Looks great and straight-forward! This is a small thing, but I think adding some space between the header and contact form, as well as increasing the font size of the form headers (maybe 25-30px or so) / overall size of the form would increase readability and fill the page better. Overall great work.

Thanks for the feedback, I added a background for the form, increased the font size, and padded a bit more to add spacing between the text.

**Pull request merged**
