### PR TITLE
Implement Content Page Mobile Scalability

### PR DESCRIPTION
**Pull request by kevinquayle**
Content pages should now be comfortable to read on both mobile devices and desktops.

FYI: I also set height and width of ContentWrap to 100%, so that percentage units within each page work correctly.

### CODE REVIEW

**Review by masakiasanuma — COMMENTED** [review]
Tested locally and it looks good to me. I was wondering though, do you think we should remove the left-right margin (marked below) when the user is on mobile? 

Screen Shot 2022-03-11 at 8 32 15 AM
 
I realized while working on the quiz result page that having the left-right margin there is a bit unnecessary when it's on mobile, so I had the page look like this:

image

What do you think?

**Comment by kevinquayle** [comment]
Yes! The quiz page looks very nice without the margins on mobile, so that is good by me.

**Comment by masakiasanuma** [comment]
> Yes! The quiz page looks very nice without the margins on mobile, so that is good by me.

Alright sounds good, can you add that in then? For now you can just do the `@media (max-width: 768px)` and set margin left and right to 0 I think.

**Comment by kevinquayle** [comment]
Updated to include that change.

**Review by masakiasanuma — CHANGES_REQUESTED** [review]
Thanks for the change! While you're at it, can you also do the same thing with the quiz page? Just removing the margin on left and right.

**Comment by masakiasanuma** [comment]
@kevinquayle Ok I just made the change and committed since we have the client meeting today.

**Review by masakiasanuma — APPROVED** [review]
Approved!

**Review by KhelanM — APPROVED** [review]

**Pull request merged**
