### PR TITLE
Close sidebar when clicking outside & push content to the side

### PR DESCRIPTION
**Pull request by masakiasanuma**
This PR fixes some minor bugs relating to the sidebar:

1. As requested by the client, the main content will be pushed to the side when the sidebar opens up.
2. Ticket that Kevin opened, the side bar will now close if you click anything outside the sidebar for fluidity.

image

### CODE REVIEW

**Review by kevinquayle — CHANGES_REQUESTED** [review]
It looks great and works perfectly on pretty much all of the pages! Some small things that I noticed:

For the home page only, when the resolution is around iPad size, contents are pushed off the screen when the side bar is opened.
image

For the home page only, opening the side bar shows scroll bars on desktop (probably related)
image

Lastly, clicking outside of the sidebar doesn't work on mobile (although disregard this if that's intentional), and black text that says "Testing" appears in the top left for a small moment when opening the sidebar.

**Comment by masakiasanuma** [comment]
@kevinquayle Thanks for the review! I'm starting to think implementing both of these features is a bit janky since there's no point in pushing the content to the side. I remember the client specifying she wanted us to move the content to the side, but I think it's much better if we just not move the content to the side and just have the close sidebar when clicking outside feature.

What do you think?

**Comment by kevinquayle** [comment]
@masakiasanuma I would agree, I believe the client's request to push content to the side was based on the pages still being interactable with the sidebar open. With the clicking outside feature implemented I think this becomes a non-issue.

**Review by valistelea — APPROVED** [review]
Great work, looks good to me.

**Comment by masakiasanuma** [comment]
@kevinquayle I made the changes, can you check it again?

**Review by kevinquayle — APPROVED** [review]
I like that the sidebar opens up completely in the mobile format! I think there is a small glitch though, where if you open up the sidebar and click on one of the pages to navigate to, the sidebar remains on the left side of the screen, and you have to click the button again to close it.

Other than that everything works correctly and it's approved by me.

**Comment by masakiasanuma** [comment]
@kevinquayle Thanks for the catching that, I fixed it.

**Pull request merged**
